#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

registration:
            path: /registration
            controller: App\Controller\RegistController::registration

products:
            path: /products
            controller: App\Controller\ProductsController::products

product:
            path: /product/{id}
            controller: App\Controller\ProductsController::product

registtest:
            path: /registtest
            controller: App\Controller\RegistTestController::registtest          

product_add:
            path: /products/add
            controller: App\Controller\ProductAddController::productadd         
    
product_edit:
            path: /products/edit/{id}
            controller: App\Controller\ProductEditController::productedit         

product_delete:
            path: /products/delete/{id}
            controller: App\Controller\ProductEditController::productdelete

categories:
            path: /categories
            controller: App\Controller\CategoriesController::categories

category_add:
            path: /category/add/{id}
            defaults: {id: 0}
            controller: App\Controller\CategoryAddController::categoryadd

category_edit:
            path: /category/edit/{id}
            controller: App\Controller\CategoryEditController::categoryedit   

category_tree:
            path: /category/tree/{id}
            controller: App\Controller\CategoryTreeController::categorytree
