#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

registration:
            path: /registration
            controller: App\Controller\RegistController::registration

products:
            path: /products
            controller: App\Controller\ProductsController::products

product:
            path: /product/{id}
            controller: App\Controller\ProductsController::product
