#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

registration:
            path: /registration
            controller: App\Controller\RegistController::registration

products:
            path: /products
            controller: App\Controller\ProductsController::products

product:
            path: /product/{id}
            controller: App\Controller\ProductsController::product

test:
            path: /test
            controller: App\Controller\TestController::test          

product_add:
            path: /products/add
            controller: App\Controller\ProductAddController::productadd         
    
product_edit:
            path: /products/edit/{id}
            controller: App\Controller\ProductEditController::productedit         

product_delete:
            path: /products/delete/{id}
            controller: App\Controller\ProductEditController::productdelete



categories:
            path: /categories
            controller: App\Controller\CategoriesController::categories

category_add:
            path: /category/add/{id}
            defaults: {id: 0}
            controller: App\Controller\CategoryAddController::categoryadd

category_edit:
            path: /category/edit/{id}
            controller: App\Controller\CategoryEditController::categoryedit   

category_tree:
            path: /category/tree/{id}
            controller: App\Controller\CategoryTreeController::categorytree



product_tocart:
            path: /product/cart/{id}
            controller: App\Controller\ProductToCartController::product_tocart

product_fromcart:
            path: /product/cart_delete/{id}
            controller: App\Controller\ProductToCartController::product_fromcart

delete_whole_product_from_cart:
            path: /product/cart/delete/wholeproduct/{id}
            controller: App\Controller\ProductToCartController::deleteWholeProductFromCart

cart_view:
            path: /cart
            controller: App\Controller\CartViewController::cartView

order_form:
            path: /order
            controller: App\Controller\OrderController::orderForm


login:
            path: /login
            controller: App\Controller\SecurityController::login
            methods: GET|POST

logout:
            path: /logout
            methods: GET


            
            
